CREATE DATABASE IF NOT EXISTS USER_APP;

USE USER_APP;

CREATE TABLE IF NOT EXISTS USER (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO USER (NAME, EMAIL, PASSWORD, USERNAME) VALUES ('admin', 'admin', 'admin', 'admin');
INSERT INTO USER (NAME, EMAIL, PASSWORD, USERNAME) VALUES ('user', 'user', 'user', 'user');
